# Lab03 : Tensor Handling

In [1]:
import numpy as np
import torch

## View (Reshape)

In [2]:
t = np.array([[[0,1,2],
             [3,4,5]],
             
             [[6,7,8],
             [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [3]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [4]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


-1은 가변인자이므로 뒤에 고정값에 따라 유연하게 변경한다. batch size등 변동성이 큰 부분에 사용

## Squeeze

In [5]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [6]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


Element가 존재하지 않는 차원을 없애 주는 역할, dim 인자와 함께 사용이 가능하다.

## Unsqueeze

In [7]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [8]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [9]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [10]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [11]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


Dimension을 늘려주는 역할

## Type Casting

In [12]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [13]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [17]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


bt = (lt == 3) 넣을시, bt = [0, 0, 1, 0] 반환. 마스킹 작업등을 할 때 사용되는 자료형

In [16]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## Concatenate

In [18]:
x = torch.FloatTensor([[1,2], [3,4]])
y = torch.FloatTensor([[4,5], [7,8]])

In [19]:
print(torch.cat([x,y], dim=0))
print(torch.cat([x,y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [4., 5.],
        [7., 8.]])
tensor([[1., 2., 4., 5.],
        [3., 4., 7., 8.]])


## Stacking

In [20]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [21]:
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z,], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [22]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## Ones and Zeros

In [23]:
x = torch.FloatTensor([[0,1,2], [2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [24]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


x와 같은 사이즈를 같은 ones나 zeros 텐서를 생성한다

## In-place Operation

In [25]:
x = torch.FloatTensor([[1,2], [3,4]])

In [26]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


mul_의 경우 In Place Operation으로, 해당 메모리의 결과값을 저장하는 연산이다.