# Lab01 : Tensor Broadcasting

In [2]:
import numpy as np
import torch

## Broadcasting

In [3]:
# Same shape
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [ ]:
# Vector + Scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
print(m1+m2)

In [5]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


## Mul vs Matmul

In [9]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1: ',m1.shape) # 2 x 2
print('Shape of Matrix 2: ',m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [12]:
print('Shape of Matrix 1: ',m1.shape) # 2 x 2
print('Shape of Matrix 2: ',m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2)) # 2 x 2 

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


mul의 경우 Broadcasting되어 Element-wise 곱셈이 발생한다.

 ## Mean

In [13]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [14]:
t = torch.LongTensor([1,2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


mean함수는 float형에서만 사용이 가능하다.

In [15]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [16]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


dim = 0, 행 없애고 열만 남기기
dim = 1, 열 없애고 행만 남기기
dim = -1, 마지막차원, 즉 1에 대해서 표현하기

## Sum

In [17]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


## Max and Argmax

max 연산은 별도의 인자가 없다면 가장 큰 값 하나를 리턴한다.

In [18]:
print(t.max())

tensor(4.)


max 연산은 차원을 지정해주면 2개의 값을 리턴한다. 하나는 최대값이고, 나머지 하나는 Argmax이다.

In [19]:
print(t.max(dim=0))
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

(tensor([3., 4.]), tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])
