# Lab01 : Tensor Manipulation

In [1]:
import numpy as np
import torch

## 1D Array with NumPy

In [3]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [4]:
print('Rank of t: ', t.ndim)
print('Shape of t: ',t.shape)

Rank of t:  1
Shape of t:  (7,)


In [6]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1])
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1])
print('t[:2] t[3:] = ', t[:2], t[3:])

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


## 2D Array with NumPy

In [7]:
t = np.array([[1.,2.,3.], [4.,5.,6.], [7.,8.,9.], [10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [8]:
print('Rank of t: ', t.ndim)
print('Shape of t: ',t.shape)

Rank of t:  2
Shape of t:  (4, 3)


## 1D Array with PyTorch

In [9]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [10]:
print(t.dim())
print(t.shape)
print(t.size())
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1])
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1])
print('t[:2] t[3:] = ', t[:2], t[3:])

1
torch.Size([7])
torch.Size([7])
t[0] t[1] t[-1] =  tensor(0.) tensor(1.) tensor(6.)
t[2:5] t[4:-1] =  tensor([2., 3., 4.]) tensor([4., 5.])
t[:2] t[3:] =  tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 2D Array with PyTorch

In [11]:
t = torch.FloatTensor([[1.,2.,3.],
                       [4.,5.,6.],
                       [7.,8.,9.],
                       [10.,11.,12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [12]:
print(t.dim())
print(t.size())
print(t[:,1])
print(t[:,1].size())
print(t[:,:-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])
